### ISSUE TITLE
Avoid duplication for messages sent to self

### ISSUE THREAD

**Issue by tetris4** [kontalk/androidclient#1065]
When I send a message to myself, I usually do it as a form of a note, so I can come back and check a link or text later.

As is, Kontalk duplicates all messages since it both stores the sent and received message.

Not sure of how this could be implemented, but it would be good to only keep one of those two.

**Comment by webratte** [comment]
I do it the same way as you.

I just delete one message after I received it.
It's not a big deal ;-)

I'm not sure. But I think it's more then a few code lines for a very small feature.
Isn't it?

**Comment by OffifialMITX** [comment]
On the other hand, it's more impressive when you're doing something that you're actually not supposed to but it works well.

On September 9, 2017 4:55:59 PM GMT+02:00, webratte <notifications@github.com> wrote:
>I do it the same way as you.
>
>I just delete one message after I received it.
>It's not a big deal ;-)
>
>I'm not sure. But I think it's more then a few code lines for a very
>small feature.
>Isn't it? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1065#issuecomment-328282187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
That is expected behaviour actually. Kontalk sends all messages to all connected resources, including itself. While this might change in the future (see: message sync across devices), for now I'm sorry but I really see this as a specific modification more addressed to Kontalk-as-note-taking-app than an advantage for the communication side. Besides, any communication tool that I know of (including email and sms) allows sending messages to yourself.

However. Since this might be presented as a preference ("Do not store messages received by your own user"), and I don't want to totally close the possibility, I'll accept patches :-)

**Comment by tetris4** [comment]
No worries. Fwiw, this was meant as a (minor) feature request, not a bug report. :)
