### ISSUE TITLE
Sometimes connection is not updated in connectivity change

### ISSUE THREAD

**Issue by manolollr** [kontalk/androidclient#243]
Sorry for my poor English :-)

Kontalk version: 3.0-beta3(36)
Mobile: Samsung Galaxy S (GT-I9000)
Android version: 4.2.2
Custom ROM: cyanogenmod 10.1.3-galaxysmtd

Option different from default (In Spanish, I don't know how it appears in English):
Desconectar estando inactivo: Nunca(Never) Why is default option 1 minute? I can't get instant messages if I dont't set it to never. Is better to disconnect? A permanent connection don't drains my battery, apparently. Perhaps too load to server?

How to reproduce problem: activate and deactivate Wifi several times.

Scenario: you are in a zone with bad wifi coverage and you often lose connectivity. When you move to a zone with good wifi coverage, you will never get new messages, until you manually disconnect from Kontalk server, wait about 30 seconds, and connect again.

Monitoring network connections, with OS Explorer, for example, you can view sometimes Kontalk binds correctly to Wifi IP (192.168....) but sometimes Kontalk always bind to mobile Internet IP, regardless you are connected to wifi or not.

**Comment by daniele-athome** [comment]
The failover seems to be handled well by the system (tested on KitKat), because the system always trigger a disconnection and then a connection event. Actually by reading the documentation it should be the right behaviour. However, there is a case where this does not happen. Please, if it happens again, send us a logcat privately.
