### ISSUE TITLE
Audio play button too small

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#282]
Kontalkversion 3.0 beta5 (38)
Androidversion 2.3.6

With my thick fingers on small display, the audio player is nearly unusable ;-)

**Comment by daniele-athome** [comment]
@acappelli do you mind taking care of this please?

**Comment by acappelli** [comment]
@daniele-athome roger that

**Comment by daniele-athome** [comment]
@webratte the actual problem is that clicking on the balloon will launch an open intent to play audio with an external player. In order to play with the built-in player you need to exactly click on the play icon. We will fix that on the new material design branch which is changing the overall UI experience completely.
