### ISSUE TITLE
Smiley button / enter button / send

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#298]
This is feature request for having a send button at the place of Smiley/ enter. Many other Android apps habe it there and i press it relly offen by mistake when i want to send...

Also i dont Quote understand the Smiley button, AS it shows me entirely different Smiley from the Smiley button that is legt of the input box. Maybe the latter one is provided by Android, i dont know. Both do Seen to work though...

Thanks!

**Comment by daniele-athome** [comment]
There is already such a preference named "Show enter key".
As for the Emoji button, the ones you see in Kontalk are internally provided (Apple theme), while the others are provided by Android system (Google theme).

**Comment by h-2** [comment]
> There is already such a preference named "Show enter key".

But the Enter-Button doesn't send, it just starts a new line! That's the problem :)

> As for the Emoji button, the ones you see in Kontalk are internally provided (Apple theme), while the others are provided by Android system (Google theme).

I think this is not very intuitive to have two different ones on by default, I would disable the internal one and maybe make an option in the settings
 - [ ] use apple Emoji theme instead of default

(just for consistency, not thaat important!)

**Comment by daniele-athome** [comment]
I think it depends on the input method you're using - and Android version. I will do some tests and get back to you. In the meantime, what input method are you using and on which Android version?

**Comment by h-2** [comment]
I am Lollipop and using the default AOSP keyboard. But I also tried with the hacker keyboard. Both times the button in the bottom right corner is either smiley or "enter" where enter actually prints a newline symbol and does not send...

**Comment by daniele-athome** [comment]
I need to do some tests, but I think it's not possible because the TextView is multiline.
http://developer.android.com/reference/android/widget/TextView.html#attr_android:imeOptions

At `flagNoEnterAction`:
> Used in conjunction with a custom action, this indicates that the action should not be available in-line as a replacement for the "enter" key. Typically this is because the action has such a significant impact or is not recoverable enough that accidentally hitting it should be avoided, such as sending a message. **Note that TextView will automatically set this flag for you on multi-line text views.** 

@h-2 I don't use other messaging app, and the Android Messaging app (SMS) does not seem implement this (Android 4.3.1). Do you have other apps to test this? And maybe send me the apk so I can disassemble it and see what they do? :-)

**Comment by h-2** [comment]
> Do you have other apps to test this? 

Telegram and TextSecure both have a "Enter Button sends" option, but on TextSecure it currently doesnt work. I will do some searching in Telegram's code, maybe I can find the relevant parts myself :)

**Comment by h-2** [comment]
I believe the option is called sendByEnter and this is the place in the UI where it gets checked:
https://github.com/slp/Telegram-FOSS/blob/master/TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
(just search for "sendByEnter")

Don't know if that is helpful...

**Comment by h-2** [comment]
From my complete and utter lack of android internals I would guess that it doesn't actually change the button behaviour (the style of the button is still a return symbol, not the send symbol), it just intercepts the call...

**Comment by daniele-athome** [comment]
Thanks @h-2, I suspected it was like that, and now that I'm looking at the code it's indeed how you said: it intercepts the enter key and simulate sending. However, since this inhibits the multiline feature, I guess removing the multiline option from the text box would have the same result.

I'll transform the "Show enter key" preference to a multichoice preference. Thans for your help!

**Comment by h-2** [comment]
No problem and thanks for Kontalk :+1:

**Comment by h-2** [comment]
I see that it now works, great! However one tiny thing, when sending with the enter button, thekeyboard disappears... this is not the case for the regular send button...

And the input field becoming a one-liner can probably not be fixed, right? (Same on SMSSecure)

**Comment by daniele-athome** [comment]
@h-2 the keyboard disappearing might be input method's fault (tried other keyboards?). I'll investigate, but I don't think we can do something for that.

For the one-liner problem, yes that's needed to make enter behave as send (because it can't understand the difference between enter key and send that way of course).

**Comment by h-2** [comment]
> @h-2 the keyboard disappearing might be input method's fault (tried other keyboards?). I'll investigate, but I don't think we can do something for that.

It doesn't disappear on SMSSecure which seems to have solved this in the same way as Kontalk.

> For the one-liner problem, yes that's needed to make enter behave as send (because it can't understand the difference between enter key and send that way of course).

Seems like a stupid android restriction, but oh well ;)

**Comment by daniele-athome** [comment]
> It doesn't disappear on SMSSecure which seems to have solved this in the same way as Kontalk.

Ok for the keyboard disappearing it was intended. It shouldn't happen though... I've opened #451.
