### ISSUE TITLE
Incorrectly Told Invalid Number

### ISSUE THREAD

**Issue by covracer** [kontalk/androidclient#314]
Hi,

When attempting to request a verification code when launching the application for the first tone after overtaking it from F-Droid, I entered the following valid phone number (well it was prepopulated but re-entering manually didn't seem to help)

[undisclosed]

and got 

Invalid Number
Please insert a valid phone number.

**Comment by covracer** [comment]
Sorry for the typos. s/tone/time/; s/overtaking/installing/

**Comment by daniele-athome** [comment]
Thanks for reporting. I've hidden your phone number from the ticket text.
This should have been fixed by #296. I'll do some tests and get back to you.

**Comment by daniele-athome** [comment]
I'm sorry @covracer which version are you using?

**Comment by h-2** [comment]
Maybe slightly related: since the crypto was changed in a previous beta older version can't seem to verify anymore. I am not sure that needs fixing, but maybe there should be some way to tell the user when the app is outdated, and that it might not work as expected? At least so long as the protocol isn't stable, yet.

**Comment by daniele-athome** [comment]
@h-2 it's not related to this, but yes we would do that in next versions (3.0 is a big staging release and it involved a lot of changes overtime, something slipped off :-).

**Comment by covracer** [comment]
It's 3.0 beta 6 (39) from F-Droid.

**Comment by covracer** [comment]
Fixed in beta 7 (40). Thanks!

**Comment by daniele-athome** [comment]
:-)
