### ISSUE TITLE
Automatically accept invitation when subscription is already 'to'

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#370]
When Alice requests invitation from Bob and it was granted, the (auto send) invitation from Bob is shown. This is unnecessary: When Alice can talk to Bob, Bob should always be able to talk back to Alice (or not?).

**Comment by daniele-athome** [comment]
Actually this should be achieved with "Subscription pre-approvals" which is the same thing you're describing (if I understood it correctly, tell me if I'm wrong) but assisted by the server.
The server will remember that the user sent an unsolicited subscribed presence and autogrants the permission to the subscriber, so they can immediately exchange messages.

However... I could use this approach as a workaround for now because pre-approval is not yet supported by Tigase (it will be in version 7.1.0 which is not coming out right now).

**Comment by abika** [comment]
>The server will remember that the user sent an unsolicited subscribed presence and autogrants the permission to the subscriber, so they can immediately exchange messages.
Exactly what I mean, this is even better
