### ISSUE TITLE
Make contact list and chat list more distinguishable

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#371]
Many people (on first usage) are confused that there is a chat list and a contact list ("I can't see anybody anymore" when there are seeing the chat list), even with the hint popup. Boths lists almost look the same and many small thinks could be improved here: 
* improve the contact list icon
* show "chats"/"contacts" in the title bar
* show two icons with left/right swap ability
* or simply make the contact entries thinner

**Comment by daniele-athome** [comment]
> improve the contact list icon

Which one? You mean the window icon or the contacts avatars?

> show "chats"/"contacts" in the title bar

Mmm I might change the contacts window title to something more understandle , but not the main window title sorry.

> show two icons with left/right swap ability

Could you explain with an example please?

> or simply make the contact entries thinner

Mmm... I don't know, it seems like forcing a difference.

**Comment by daniele-athome** [comment]
Anyway I'm surprised people are confused especially because most people already use Whatsapp which follows a similar UI workflow right?

**Comment by abika** [comment]
> Which one? You mean the window icon or the contacts avatars?
The "pen" icon that you see when the list of chats is shown. Maybe add a big "plus" sign to it. On a second thought, this should already be enough

> Anyway I'm surprised people are confused especially because most people already use Whatsapp which follows a similar UI workflow right?

y, its hard for me to tell what the difference actually is

**Comment by ameenross** [comment]
Actually, I'm not sure whether following Whatsapp's example here is a good thing. I found it very confusing when I first started using it. I must not be the only one with this problem, especially as I'm a power user. Though because of Whatsapp's market share, people have gotten acquainted with their *app*, rather than their *UI language*.

Personally I would opt for a group/contacts icon instead of a pencil (or instead of an "add chat" icon in Whatsapp's case). Adding a window title "chats" is helpful as well.

An alternative is to make a tabbed interface, where the first tab contains the chats and the second lists all contacts. You can enable swiping between the two tabs, which is much easier user interaction. This is similar to Antox for example, so I have hands-on experience. It's quite an enjoyable UX.

**Comment by daniele-athome** [comment]
I'm not really keen to introduce a tabbed interface.
Also changing the main window title it's a big thing. I'll think about it.

As a first and quick change, I could use the icon used in AOSP Messaging app (which is the same used by Whatsapp by the way).

**Comment by TheLastProject** [comment]
Instead of making it more distinguishable, guiding people through the app with a "showcase" view may be a thing to consider as well. Something like https://github.com/JesusM/ShowcaseViewLibrary, perhaps (I haven't tried the library at all, but it shows the idea).

**Comment by h-2** [comment]
I thought about this, as well, my completely different take would be:

  * have only one combined view
  * make a button that switches between sort-by-date and sort-by-name in the menubar
 
-> IMHO this would greatly reduce complexity since all people and all conversation can be reached by scrolling; the different sortings represent the two different windows; maybe not too difficult to implement?

**Comment by daniele-athome** [comment]
@h-2 sorry but that IMO will confuse people to the extreme :-) it would mean that you always have all your contacts in your main screen. Also, because of this clear separation also in the application database and code, it would not be an easy implementation.

@acappelli what's your opinion on @h-2 idea?

**Comment by ameenross** [comment]
I don't like the idea either.

**Comment by h-2** [comment]
@daniele-athome my reasoning was that after a while you will have written all (or most) of your Kontalk-Contacts a message, so they will all appear on the first screen anyway. Now the default screen, is the list of conversations, so the most intuitive was for me to text one of my contacts, is to scroll through list and pick the contact. 
Now there will be few (<10%) which I won't find in the list at which point I will switch to the second list (the full list of contacts). That's why I thought it would be good to have everybody on the first screen right a way. :smiley_cat:

**Comment by ameenross** [comment]
I'd like to note that I just noticed that whatsapp has actually implemented the tabbed interface I just described. They have a third tab "calls" though. I also noticed something strange: I have installed whatsapp through the apk, and this update happened automatically... Possibly date activated?

**Comment by daniele-athome** [comment]
@ameenross yes, voip calls have been in the app for several weeks now.

**Comment by ameenross** [comment]
I haven't seen it before today (have I missed it? :confused: ). Unless the APK now has a method to self-update (which sounds inlikely) the code must have already been there and was date-activated or smth. Anyway, that's not what the issue is about.

If you want Kontalk's UI to be similar to whatsapp's, the tabbed interface is really a positive thing about it IMO.

**Comment by abika** [comment]
I'm also against tabs (in contrast to my previous post). The chats list should be the "main" view, a user would open the contacts list normally only for a short time for selecting a contact.

A new idea I had is showing the contact list inside a [navigation drawer](https://developer.android.com/design/patterns/navigation-drawer.html) opening from the right side. When I have time, I will try implementing this myself.

**Comment by daniele-athome** [comment]
@abika that's more like it. Google used to use it on first version of Hangouts but dropped it after a while, replacing with the tabbed interface. I don't know... it's kind of a user preference to me (that is, a point of view).

**Comment by daniele-athome** [comment]
Thanks @abika that's great work! I'll begin reviewing it and merging it to master ASAP.
By the way do you have any proposal for merging this to the material branch? I mean do you think still using a floating action button would be ideal in this situation? Any other UI insight might be useful.
