### ISSUE TITLE
Sometimes messages don't get marked as received

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#373]
Excuse the horribly broken screenshots. AndroSS does not seem to like Dimmer /at all/. Anyway, I have noticed sometimes messages don't get marked as received (only one checkmark instead of two). I have confirmed out-of-band that the messages did arrive.

![2015-03-31_00 43 53](https://cloud.githubusercontent.com/assets/1885159/6924533/8a921df6-d7d9-11e4-8c86-0070adc398e5.png)
(Third message on my side wasn't marked received)

![2015-03-31_00 44 04](https://cloud.githubusercontent.com/assets/1885159/6924534/8ab24a40-d7d9-11e4-806a-f25e53990951.png)
(Second message on my side wasn't marked as received)

These messages remain marked as sent but not delivered almost 24 hours later.

**Comment by daniele-athome** [comment]
Thanks for reporting. I've been having this issue myself. It's a long time problem with Tigase that we're trying to settle together with Tigase team. This is caused by delivery receipt messages being bounced back to the sender because of a specific failure that happens in a rare case of very bad network situations.
In the meantime I'll implement something to retry sending the delivery receipt.
