### ISSUE TITLE
question: How works invitation?

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#382]
I don't understand invitations :-\

Can you clearefy it please?

My special case:
* I have already Kontalk
* Alice (number in my phonebook) installed it first time.
* Alice get a invitation from me.
* Alice accept the invitation
* Alice is shown for me as online (later as  "Last seen...")

I think I should first also accept a invitation from Alice before we can chat?

At the moment we have not chattet yet.

Thank you.

**Comment by daniele-athome** [comment]
That is actually a normal XMPP subscription flow: invitation is dual. You have to accept her invitation and she has to accept yours.
This might be strange (it is :-) but that's the way the protocol is), but can be simplified using subscription pre-approval. That is, you send an "invitation accepted" message in advance, so that as soon as the other party requests an invitation, it's automatically accepted by the server and you can start chatting.
Unfortunately, subscription pre-approval is not supported on Tigase yet (and it's not an easy thing to do without their help, but they are very busy on other things right now). They planned it for Tigase 7.1.0, but no date is available as of now.

**Comment by daniele-athome** [comment]
One more thing to add: the Android client already supports subscription pre-approval, so the moment will be implemented on the server it will be automatically available to everyone.

**Comment by webratte** [comment]
Sorry, I think you misunderstand me.
My problem is not the dual invitation. I like it.
So nobody can spam me without ask me before ;-)

I have never get a invitation from Alice but could write her I think (I have not tried it yet but can see her onlinestate like "online" and "last seen").

**Comment by daniele-athome** [comment]
The dual invitation does exactly what you're saying. XMPP subscription is bidirectional. If Alice accepted your invitation, you will be able to write to her, but not necessarily the opposite (you can see that because you don't get delivery receipts which are actually normal messages).

**Comment by daniele-athome** [comment]
Writing to her means that you can also see her online status of course.
