### ISSUE TITLE
Message missed

### ISSUE THREAD

**Issue by massimobarbieri** [kontalk/androidclient#416]
Hi,
this is the second time it happens to me: I sent two messages in quick succession, and the people I wrote receives only the second one. Unfortunately I try to send messages quickly but the bug is not reproducible. Perhaps you can investigate the server side on the date and time of the message?
In this case I can provide private accounts with whom I have exchanged messages.
Thanks for your work.
Max

**Comment by daniele-athome** [comment]
Thanks for reporting. Please send me an e-mail with the phone numbers (or user ids) of the other user and date/time of a lost message and the next one that was delivered successful.
P.S. when you say "he receives only the second one", do you mean that he doesn't receive the message at all or you don't get a delivery receipt?

**Comment by webratte** [comment]
Hi @massimobarbieri 
are you sure the first message is not received?
I have a similar problem sometimes. 
I write a message but the second chekmark are not shown.
But the message are received.

This is happens if my GSM connection is bad I think.

**Comment by webratte** [comment]
@daniele-athome 
Oops your are faster then I ;-)

**Comment by daniele-athome** [comment]
That's exactly what I was talking about :-) this a server-related problem which happens in very bad situations at the recipient's and/or the sender's side. I've already working on it along with Tigase time, but it's gonna take some time because I'm busy now with preparing my talk in Milan next wednesday.

**Comment by massimobarbieri** [comment]
Hi,
I'm very happy to know that this developer page is so active! ;-)
I got the delivery with the double chekmark but the number I sent didn't receive the message.
Thanks again for your work!
Max

**Comment by daniele-athome** [comment]
Ok that's not good. I remember of a recent bug that was fixed in latest release which prevented some messages to be saved locally... what version is your friend using? Do you have access to a catlog from that device?

**Comment by massimobarbieri** [comment]
Both clients runs Kontalk 3.0-rc3 (48). I can access to the device of my friend maybe monday...
Ciao,
Max

**Comment by svrnwnsch** [comment]
@webratte @daniele-athome is there a issue open for the problem that you get only on check mark for first message even if it was received? I am having the same problem sometimes, when I have only edge.

**Comment by daniele-athome** [comment]
@svrnwnsch it's a Tigase bug, it's not here.

**Comment by daniele-athome** [comment]
@massimobarbieri can you produce a logcat from the your friend's device when this bug happens? I can't really find anything wrong on the server side, and because you have the double tick it means there is some problem storing the actual message on your friend's device (which can happen for a number of reason, most of them not related to Kontalk itself e.g. no space left on device, but let's investigate anyway).

**Comment by massimobarbieri** [comment]
@daniele-athome Yes I will as soon as it happens again! Many thank for your investigation on this!

**Comment by daniele-athome** [comment]
Hi @massimobarbieri any news on the issue?

**Comment by massimobarbieri** [comment]
Hi @daniele-athome the problem doesn't happens anymore....

**Comment by daniele-athome** [comment]
Ok, I'll mark this invalid for now. Feel free to reopen it if it happens.
