### ISSUE TITLE
Slow thread loading due to history size

### ISSUE THREAD

**Issue by donjan** [kontalk/androidclient#447]
I've broken the 10k message count in a few threads (consider this a testament to the usefulness of Kontalk over the past couple of years!) and the loading time for opening them is getting mildly irritating (3-4 seconds).

Deleting the threads is a bad option. I can pull the text from my phone and store it elsewhere, but ideally it should be searchable within Kontalk.

So this feature request would be either of these:
- improve performance of thread loading (maybe introduce chunk loading, only the last 1kb, the rest on demand/scrolling)
- add an "archive thread" option below "delete thread"

Side note: how about reintroducing some kind of message count display in 3.0?

**Comment by daniele-athome** [comment]
Thanks for reporting. First of all, I would like to know what device you're using so we I can do some performance comparisons (I myself own also a Huawei U8150 which behaves well despite being very low-end).

About an actual solution: I'm more keen to use chunk loading, but I need to do some experiments because it might not be possible without actually splitting the database file into actual chunks.
"Archiving" a thread should happen automatically, as in you need to manually load the older chunks, still you can search on them. I could leverage on #104 and use the backups to make searches and "merge" the results with the internal database file, however I'll need some mechanism to "swap out" messages to the external storage from time to time. I'll investigate among the possible solutions and get back to you. In the meantime, any other suggestion or comment is of course appreciated.

**Comment by donjan** [comment]
Thanks for looking into it. I'm running on a HTC Desire S with a rooted but fairly standard configuration (Android 2.3.5, no system changes, default SD card). And just to mention: low message count threads load snappily. My largest thread had a counter of some 11k+ before upgrading Kontalk to 3.0.

Chunk loading is the elegant option, but seems to require quite some extension of Conversation / MessagesProvider / ... . Slicing up the database should be avoidable if you keep track of the currently loaded pieces (position references) and carefully select the further requests.
Archiving might IMO be better as a user-initiated decision (assuming it's the "export" kind of archiving), but it's your call.

Anyhow, I'm happy with whatever you think is the more pragmatic choice (I'm afraid I can't in the foreseeable future afford the time to contribute properly), i.e. if you already have something on the way for https://github.com/kontalk/androidclient/issues/104.

**Comment by TheLastProject** [comment]
Is there any reason you can't simply load chunks from the database? It seems to be SQL, what would prevent you from loading only the last 100 with a query like:

`SELECT * FROM " + TABLE_MESSAGES + " WHERE thread_id = ... ORDER BY date DESC LIMIT 100` (I just made the query up, I have no clue what the correct one would actually be)

And automatically prepending another 100 when the user reaches the top 5% when scrolling up? Or, even better, selecting by date?

**Comment by daniele-athome** [comment]
@TheLastProject ListView doesn't work that way: it uses a single cursor for backing its data. I might "merge" multiple cursors (that is, vertically, from multiple queries) but I don't know if it's a good thing to do in a performance (see: memory+time) point of view.
Also, I don't think "redoing" the query by adding a LIMIT clause and passing the cursor to the ListView again would be very helpful, because the ListView will reload all data from scratch.
Although, I have to say I still need to investigate the possibility of "adding data" in such a way while using ListView. What I wrote here is from my current knowledge only. I'll post my foundings and experiments here.

**Comment by daniele-athome** [comment]
I'm afraid I have to delay this to the next release. I'm already late with 3.0.2 and I had no time to properly figure out what to do for this yet, sorry.

**Comment by daniele-athome** [comment]
I'm sorry I didn't have much time to properly look into this. I'm going to delay it to 3.1 because I want to push material design to be released as soon as possible so I don't have to keep track of two development lines.

**Comment by donjan** [comment]
No worries, I won't complain when I'm not contributing. Looking forward to better performance though ;)

**Comment by daniele-athome** [comment]
Using MergeCursor doesn't work apparently. I need to make some more tests, in the meantime 06e41b1 introduced some stuff that will be useful later.

**Comment by daniele-athome** [comment]
I've just pushed a first implementation of pagination, 1k messages per page should be enough for a start (it's hard-coded for now). It seems to work fine and the performance impact after many pages doesn't seem to be so big. You'll see this on 3.1.2 soon anyway, please provide all the feedback you can since this feature is experimental.

**Comment by donjan** [comment]
Unfortunately I have bad news from your perspective: I've switched to the new Signal release (previously TextSecure). Not sure when I'll be testing Kontalk again as all my contacts have moved off too.

**Comment by daniele-athome** [comment]
@donjan you traitor :P
Just kidding, it's quite normal. They have more resources than this little project. But I'm not giving up just yet :-)

**Comment by donjan** [comment]
Hehe, I know how it feels, but that's social dynamics... (at least I'm pulling folks off of WhatsApp)
Keep going and have fun!
