### ISSUE TITLE
Unsubscribe from non-existing users

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#464]
After a user account expires, unsubscribe automatically during sync.
Be sure that the account actually doesn't exist any more. For example, if a remote server is down, entry in roster match response will not be there, effectively marking the user as non-existant. Do something about it, for example set a grace delay for user expiration (where do we store it?).

**Comment by h-2** [comment]
Out of curiosity: it this kind of communication with the server encrypted? Otherwise I could see a possible attack vector where a MITM could suppress the response, thereby initiating unsubscription in the client, then let the user reappear and send a new (compromised) key. This would be a rather sophisticated attack, but quite doable for the NSA ;)

Altogether I think there should always be some prominent notice when the key changes on another user. Maybe if we have a "Contact Settings" page sometime (where you can define user-specific privacy settings) we could also have
  * last key change: 2015-03-15

Or something like that. It wouldn't be visible unless looked for, but it means that any kind of attack involving a MITM (or the server) would be much easier to notice.

**Comment by daniele-athome** [comment]
> Out of curiosity: it this kind of communication with the server encrypted? Otherwise I could see a possible attack vector where a MITM could suppress the response, thereby initiating unsubscription in the client, then let the user reappear and send a new (compromised) key. This would be a rather sophisticated attack, but quite doable for the NSA ;)

Client-server communication is encrypted of course, and this kind of attack would be mitigated by the user when the new invitation arrives - with a different key. The user will need to accept that first.

As for the contact settings page, it should be part of #300 and #456, although no serious design have been put on it yet.
