### ISSUE TITLE
Push for non-GCM environments

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#466]
I currently use polling (f-droid version) which works okay, but sometimes results in having to wait for 15min... (I know I can configure it)
Could we keep an issue open for the long term, to solve this better? It seems like many projects would need this, but the solutions aren't perfect, yet.

Here are some more links:
http://stackoverflow.com/questions/20329403/android-push-notification-without-using-gcm
http://stackoverflow.com/questions/14629490/android-push-message-without-gcm-possible
https://developer.motorolasolutions.com/docs/DOC-2315

**Comment by daniele-athome** [comment]
The issue of push notifications has been a long running debate for years :-)
Push notifications is a very silly technology if you think about it: Google Play service on your device just stays 24h connected to GCM servers and waits for data (that is: a push notification).
The advantage of using GCM is that a single service stays always connected, waiting for data and consuming energy and bandwidth. I could use another service to do the same thing, but it would mean another background service handling another connection, consuming energy and so on.

Instead of doing that, Kontalk can stay always connected if you set "Disconnect when idle" to "never". It will work as if it's using a push notification technology, consuming as little energy as possible. In fact, I'm thinking of setting that preference to "never" as default, because it doesn't consume so much afterall.

**Comment by mimi89999** [comment]
> In fact, I'm thinking of setting that preference to "never" as default, because it doesn't consume so much afterall.

:+1:
