### ISSUE TITLE
PGPCoder is signing with certification (primary) key

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#468]
This shouldn't be happening.

**Comment by abika** [comment]
Is this the reason for the currently failing message signature checks?

Also, I guess the Desktop clients needs to be adapted to f4c81dbf57b38559c7e57e2544655829ab4e347e ?

**Comment by daniele-athome** [comment]
Hi @abika, I was going to write you down a few lines on this. I've used the last couple of days to fix some stuff in encryption. Cross-certification (the commit you mentioned) is one of them.
At first, version 3.0 featured a fix for encryption and signing that made Kontalk choose the right key for the right task. But again, just a couple of days ago, I found out it wasn't working correctly, so I fixed it once more in the four last commits.
You should backport the fixes in `PGPCoder` to the deskop client. If you need help knowing what they are just contact me.
Also **I'd like to move the `org.kontalk.crypto.Coder` class to client-common-java** so we can both rely on the same interface. Do you have suggestions to make it more "portable"? I see you didn't backport PGPCoder at all, **do you think we may benefit from moving the Coder class to common?** Also do you think sharing the whole `PGPCoder` class would be feasible? Of course copying the source file is necessary because of Bouncy Castle package names, but it still would mean reusing stuff (`PGPCoder` is platform-independent).

**Comment by daniele-athome** [comment]
And yes, that is way the signature check is failing.

**Comment by abika** [comment]
Hard questions here. First, about the PGP changes:
I adopted most of the changes. Cross-certification is only done for new keys, so the Desktop client doesn't need this, correct?

About the code sharing:
I suggest instead of sharing `Coder` and/or `PGPCoder` let's only focus on some static methods for the most basic PGP actions (de-/encrypt of text/files) so we can both use them easily:
* no use of output parameter (except the output file stream)
* instead returning static classes with the result including all errors that happened as exceptions xor enums
* remove dependencies from other classes (`PersonalKey`)

This is basically what PGPCoder is doing but the details differ. This way we both don't need to change much code.

Continue the discussion at client-common...?

**Comment by daniele-athome** [comment]
> I adopted most of the changes. Cross-certification is only done for new keys, so the Desktop client doesn't need this, correct?

Yes, until we include registration in the desktop client too.

>  suggest instead of sharing Coder and/or PGPCoder let's only focus on some static methods for the most basic PGP actions (de-/encrypt of text/files) so we can both use them easily:

I guess you're talking about e.g. `org.kontalk.crypto.PGP`?
The problem with encryption classes is that Android classes reference Spongy Castle package names but desktop's reference Bouncy Castle package names, that's why I was more keen to extract a common interface to generally encrypt/decrypt stuff suitable for all Kontalk clients, which would be fine for all platforms.

Can you elaborate on your proposal? I didn't get your list of points quite right sorry. Specifically:

> * no use of output parameter (except the output file stream)

What about errors?

> * instead returning static classes with the result including all errors that happened as exceptions xor enums

This one I don't understand. Didn't you say *no output parameters*?

> * remove dependencies from other classes (`PersonalKey`)

This one can be arranged, but it depends on what you want to put into client-common-java.
