### ISSUE TITLE
Add temporary code to delete .nomedia from pictures folder

### ISSUE THREAD

**Issue by juanito003** [kontalk/androidclient#479]
When downloading a picture from a friend, we can only open the picture in Kontalk. I don't know where the jpeg file is stored to open it from my gallery manager or file explorer.

Is this a bug or a feature? In previous version 3.0 rc3 or rc4 it was saved in Kontalk folder.
It would be nice to have this again.

**Comment by daniele-athome** [comment]
It's a bug caused by version 3.0 which created a .nomedia file in the Kontalk folder. For now you can workaround it by deleting the file manually (it won't be created again by the app), however, in order to counteract this problem, I probably should add some code to delete the .nomedia file. I'll add a temporary fix.

**Comment by juanito003** [comment]
Thanks, I deleted it and it worked.

**Comment by daniele-athome** [comment]
This fix will be removed in next milestone version by #486.
