### ISSUE TITLE
federate with TextSecure network

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#492]
Currently we have two competing services trying to do the same thing - end to end encrypted federated chat with phone number based identification. This splits the community efforts. Would it be possible to implement axolotr protocol for communicating with TextSecure users?

**Comment by TheLastProject** [comment]
There would surely be a lot more necessary than axolotr crypto to make Kontalk and TextSecure federate, because Kontalk is based on XMPP and TextSecure something else altogether. Doing this would be a complete nightmare.

axolotr implementation would be nice to have, as it is a pretty nice crypto system, but making Kontalk and TextSecure federate seems way out of scope. To be honest, Kontalk is the only real fully free option on a non-Gapps device anyway, TextSecure doesn't work without Google Play.

**Comment by daniele-athome** [comment]
@TheLastProject you took the words right out of my mouth :-)

**Comment by pravi** [comment]
Brilliant, lets make 10 more non-interoperable protocols, networks and apps each so each can claim their idea is only right/pure and everyone else is stupid.

https://github.com/siacs/Conversations/issues/1273

**Comment by TheLastProject** [comment]
Brilliant, let's yell at the developer who switched from his own protocol to XMPP, which is a standard protocol, for interoperability and who has it implemented in a way where you can just add Kontalk users from other XMPP servers. What about actually suggesting things instead of yelling without doing your research? Kontalk's reason for phone number hashing is well-documented: user privacy.

**Comment by pravi** [comment]
I did suggest a way for interoperability but it was not accepted by conversations developers. See the issue linked above. If conversations implement an option to add kontalk users by phone number, it would make interoperability easier between kontalk and the rest of xmpp. But they think this means supporting a stupid idea.

**Comment by pravi** [comment]
TextSecure is also Free Software, so gapps dependency could be removed. Making Kontalk not interoperate with TextSecure splits the Free Software network.

**Comment by TheLastProject** [comment]
Oh, your message sounded like you were blaming Kontalk, while @daniele-athome has put a lot of work already in federating properly.

And technically, Gapps can be removed from TextSecure, but the TextSecure developers refuse to accept patches to remove the Gapps dependency: https://github.com/WhisperSystems/TextSecure/issues/1000 (very long discussion). The TextSecure developers really don't care about software freedom.

**Comment by pravi** [comment]
@thelastproject the very idea of Free Software means we are not under mercy of developers. Since TextSecure is federated, we could run a version that does not need google cloud messaging/gapps on our server and still talk to other TextSecure users. Now I'm forced to use both TextSecure and Kontalk since some of my friends movef to TextSecure from Android and some to Kontalk. Kontalk server could talk the TextSecure protocol and interoperate with TextSecure protocol. If it is only about the work involved that is fine. If you would be willing to accept patches, I can try to find some folks to implement it.

**Comment by TheLastProject** [comment]
@pravi Actually, the TextSecure server supports sockets, but they refuse to add support in the client, even though someone else added patches.

While being able to chat with TextSecure users from Kontalk would be nice, I do not think that that would be possible without basically rewriting Kontalk from scratch, just not worth the time and messy code you will have as a result, especially because having two IM apps installed is really not that horrible (you are lucky you can even use TextSecure, I can't because I don't run the Google Play malware on my phone).

**Comment by h-2** [comment]
> Kontalk server could talk the TextSecure protocol and interoperate with TextSecure protocol.

Also note that TS does not automatically federate, so you cannot tallk server to server. TS developers have repeatedly stated that they demand even forked clients not interact with their servers, and Free Software or not, they could enforce this through client-keys shipped only in their binaries.

I am upset about the fragmentation of Free Software messengers, too, but I think Kontalk is the least to blame in the whole situation, because they are trying the hardest to use open standards and allow federation. Also I have not seen @daniele-athome rant about other people or calling their decisions "stupid", unlike other developers.

@pravi if you have time and/or engineering resources, you could help out with Kontalk directly. Or maybe work on a Telegram plugin for Kontalk. it could use more secure defaults than Telegram and would allow Telegram users to switch without losing friends. Telegram is rather open about allowing other clients to connect, and has one of the largest userbases after WhatsApp I think (at least in Germany).

**Comment by daniele-athome** [comment]
Seriously @pravi how could implementing any IM protocol that comes out into one app be of any advantage to the standardization of such protocols? Kontalk has one purpose: to use XMPP with phone numbers. I chose XMPP because it can be federated, but I won't expand that to other networks too - there is simple too much work to do for just that.

Something that **might be** useful for Kontalk by TextSecure is the Axolotl Protocol used for encryption, with some adaptions for using it with XMPP (a XEP might be a nice thing too have by the way).

**Comment by witchent** [comment]
Just wanted to add some stuff, hope you don't mind.
First of all, I am running textsecure on a gapps free nexus 4 on the production server. For anyone interested: (https://github.com/JavaJens/TextSecure)
Secondly, even though it works, I am still concerned, because moxie0 really defends gcm and opposes every try to get rid of Google. Therefore I am a bit concerned he might decide to remove the server support if he thinks javajens implementation is insecure or whatever (and that is his call to make as he's the maintainer.
The reason why I still use it and not kontalk is that it just works. You guys are doing a really good job, but iI dont have someone to try around with in the moment, and the last few times there were to many problems (like not being able to chat after importing keys) and its easier to convince friends of using textsecure.
Well long story short, I think its better to concentrate on your open protocol then to adapt one that is at the sake of someone who does not value freedom of choice as highly as you do.
Hope I did not misunderstand something and sorry for my English.

**Comment by daniele-athome** [comment]
Thanks @witchent, we are constatly fixing bugs and improving Kontalk. You should give it a retry now and then :-)

**Comment by witchent** [comment]
Oh I will, but first I need to find someone who is keen to help me with that again, as testing a chat program on your own is pretty boring ;-)

**Comment by pravi** [comment]
Just for the record, I'm using LibreSignal without google apps from https://fdroid.eutopia.cz/ It is not officially supported, but works well.
