### ISSUE TITLE
Timestamp inconsistencies

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#513]
As I see it there are two timestamps for every message: time-sent and time-received. By default the time sent is displayed in the messagebox, but the date is grouped by time-received. Also in the conversations overview (main window) the time is time-received.

This means in practice:
  * someone sends me a message on Oct, 3rd, 15:00, but my phone is off
  * I turn on the phone on Oct, 6th, 17:00
  * in the conversation the message is displayed as 15:00, but under day "Oct, 6th"
  * in the main window the last activity indicator shows 17:00

This is confusing, I think it should always use time-sent everywhere. Or not?

**Comment by daniele-athome** [comment]
I actually think of the timestamp in the conversation list as "last time conversation changed". But you're right it might lead to confusion... what do you suggest? Using time-sent everywhere?

**Comment by TheLastProject** [comment]
Personally, I feel time-sent would be best, because people may send messages like "See you in an hour". If Kontalk displays the time-received instead of the time-sent on those messages, it could lead to confusions. The downside would be that Kontalk would seem less responsive if the timestamps are off more, but I feel that the pros of using time-sent everywhere outweigh the cons.

**Comment by h-2** [comment]
> what do you suggest? Using time-sent everywhere?

Yes, I think that would be the best!

**Comment by daniele-athome** [comment]
Delaying to next version because it requires some minor modifications to MessagesProvider.
