### ISSUE TITLE
Outgoing files attached through Kontalk cannot be opened in gallery

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#539]
![screenshot_2015-08-25-17-48-55](https://cloud.githubusercontent.com/assets/1885159/9471691/cd5b4946-4b51-11e5-84ba-261dcfc1bd46.png)

Android 5.1.1 with an unofficial CyanogenMod 12.1. Another official CyanogenMod 12.1 could reproduce the bug. Also an Android 4.4 user.

Please note that the thumbnail is displayed just fine, so this is not in any way related to #374.

How to reproduce:
1. Open a conversation
2. Attach a picture using the attachment menu in Kontalk
3. Click the outgoing message with the attachment

Note: I waited until the image was sent before clicking it, my device didn't seem to like it if I didn't wait patiently.

The Android gallery gets the following exception and will not show the image:
```
W/ActivityManager( 2002): Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{31e4d9fb 8258:com.android.gallery3d/u0a37} (pid=8258, uid=10037) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
W/Worker  ( 8258): Exception in running a job
W/Worker  ( 8258): java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{31e4d9fb 8258:com.android.gallery3d/u0a37} (pid=8258, uid=10037) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
W/Worker  ( 8258):      at android.os.Parcel.readException(Parcel.java:1546)
W/Worker  ( 8258):      at android.os.Parcel.readException(Parcel.java:1499)
W/Worker  ( 8258):      at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3350)
W/Worker  ( 8258):      at android.app.ActivityThread.acquireProvider(ActivityThread.java:4661)
W/Worker  ( 8258):      at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2533)
W/Worker  ( 8258):      at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1442)
W/Worker  ( 8258):      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1064)
W/Worker  ( 8258):      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
W/Worker  ( 8258):      at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:778)
W/Worker  ( 8258):      at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:733)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage.openOrDownloadInner(UriImage.java:105)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage.openFileOrDownloadTempFile(UriImage.java:80)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage.prepareInputFile(UriImage.java:167)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage.access$100(UriImage.java:41)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage$RegionDecoderJob.run(UriImage.java:174)
W/Worker  ( 8258):      at com.android.gallery3d.data.UriImage$RegionDecoderJob.run(UriImage.java:171)
W/Worker  ( 8258):      at com.android.gallery3d.util.ThreadPool$Worker.run(ThreadPool.java:133)
W/Worker  ( 8258):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Worker  ( 8258):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Worker  ( 8258):      at java.lang.Thread.run(Thread.java:818)
W/Worker  ( 8258):      at com.android.gallery3d.util.PriorityThreadFactory$1.run(PriorityThreadFactory.java:44)
```

Important note: Images shared to Kontalk using the Android share menu, not attached from Kontalk itself, will open just fine.

**Comment by daniele-athome** [comment]
This is one of those issues that makes me place a bomb in the basement of a building in the Googleplex :-)

Android 4.4 (API 19) introduced the almighty [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html), along with the new MANAGE_DOCUMENTS permission. This new API is used to put all user content (photos, videos, documents) under a single "documents provider" which can be "filled with content" by any application (e.g. a gallery app or a file manager).

Now, the way Kontalk access attachments are two:

* through the share button of some app: an intent with a data URI **provided by the app** is sent to Kontalk, which is usually (i.e. most apps do that) granted access for the lifetime of the data (e.g. a real path on the file system)
* through the attachment button from within Kontalk: this button asks the system to provide some file to send. On Android 4.4+ it means accessing files through the SAF. When you access documents that way, the returned URI is granted **temporary permission** to Kontalk, in order to allow the app to read the content. Kontalk stores that URI inside its database for later access (for the "View image" menu item, which opens the gallery app).

When you choose "View image" with an image picked through the SAF, Kontalk just starts an activity the SAF-provided URI (to which Kontalk has already lost access by the way, and it has no way of retrieving the original path on the filesystem - it's an abstraction afterall).
Any application that needs access to a SAF-provided URI needs to have the MANAGE_DOCUMENTS permission or needs to be given the temporary permission I talked about before (granted only when dealing with a file in a given moment, so it's not an option for gallery apps).

Summary: the stock Android gallery app doesn't have the MANAGE_DOCUMENTS permission so it can't access SAF-provided content URIs. Sorry.

**Comment by TheLastProject** [comment]
While I agree this is an Android bug, this still does not help Kontalk look great. Telegram seems to work around it by implementing its own internal gallery, which is obviously a lot of work.

How does it sound to store sent images somewhere on the file system that Kontalk can always access? Currently, pictures taken with the camera option while in Kontalk gets shown in a "Kontalk" directory in my gallery.

If these attached images get copied to a place with .nomedia in the directory, they wouldn't even cause duplicate entries in the gallery. While still hacky, it seems like a reasonable workaround for this issue.

Please reopen this issue, at least until you have decided on this suggestion.

**Comment by daniele-athome** [comment]
Actually I need to do some tests first because of something I recently discovered. I'll get back to you.

**Comment by daniele-athome** [comment]
I've worked around the issue altogether in 161e23ec790cfc4df8c62fc8efdd6a2d4157ac5d.
