### ISSUE TITLE
Contact list loses display names

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#554]
And it shows just the hash usernames. I think it happens when trying to find new contacts. This is very annoying and makes kontalk mostly ususable, chat list and message history is the only way to find users.

**Comment by pravi** [comment]
It comes back to normal after refresh. But I doubt if most people realize it.

**Comment by TheLastProject** [comment]
I have had this happen for a few contacts, but not for most. It were contacts I haven't talked through for a while, so I thought it could be that they simply unregistered, but I'm not quite sure. They don't come back after a refresh for me, but they still show the image and phone number that they are registered on in my contact list.

**Comment by daniele-athome** [comment]
To properly map phone number hashes against phone number, Kontalk keeps a copy of all your contacts in a local database. When this database not yet created (e.g. after first registration), it takes a while to rebuild it because it needs to complete a full sync first (checking for registered users against the server). This can be solved by separating the mapping table and generating it immediately before contacting the server for the sync process.

@TheLastProject I didn't understand your case though. If a contact doesn't exist anymore (account expired) it will disappear from your Kontalk contact list, but if you have a conversation with him/her still stored in the app, it will take data from your system contact. Am I getting this right?

**Comment by webratte** [comment]
I have a similar issue.
On my contact list are two contacts who don't use Kontalk anymore since more then 6 month. The Kontalk account on there phones are deleted.
In my Kontalk contact list is shown the phone number, the profile picture and the hash of this contacts. 
The phone numbers are still stored in the contact App of my phone.

I attached a screenshot. The contacts I mean are the last two contacts.
![kontalk](https://cloud.githubusercontent.com/assets/6864851/10116057/e01b73fe-6423-11e5-8013-532af9690c7c.png)

**Comment by daniele-athome** [comment]
Ok, that shouldn't happen. If the number is stored in your contacts it should show the name, not the hash. And the combination itself is strange: it shows the hash and the number, like if the contact exists but if somewhat unnamed. @webratte is something particular about those two contacts? I mean are they stored multiple times or do they have multiple numbers in them?

**Comment by webratte** [comment]
Both see normal Contacts and only one time stored.
There are two numbers stored in contact card (mobile and home number).
But thats the same like all other contacts.

The only thing is, they don't use Kontalk anymore.

If just imported my key into kontalk on a other phone.

After refresh the conacts there is the same issue.

It looks like it comes from the server ?!

**Comment by webratte** [comment]
@daniele-athome I have just registered one of this numbers (my test number on a old test phone) and now it's all good for this number. 
There wars only a "new key" warning. And that's correct i suppose because I got a new key for this number.

Should I delete the account on my test phone to see what happens in a few weeks when the server deletes the account automatically? 
If you like I can give you this number if you have some things to check out on the server. This number is not for daily use. I use it only for testing.

**Comment by daniele-athome** [comment]
@webratte, you may delete that account if you wish, but I guess I'll be doing some tests locally to speed up things (I can't wait a month to test it ;-) and I don't like to touch the production database manually). Thanks anyway, I'll keep you posted.

**Comment by h-2** [comment]
Same here, three of my contacts haven't used Kontalk in a long time (or possibly deinstalled) and now it shows picture and number + hash (instead of name).

**Comment by realdmitchell** [comment]
I too have the number + hash (instead of name) issue. This happened after I re-flashed my kitkat. Reinstalled from F-droid and import keys. I have no pictures, no names for these contacts.

**Comment by daniele-athome** [comment]
@realdmitchell that's because Kontalk doesn't know about contacts yet. After a few moments it should be back to normal (try to just close Kontalk contacts list and reopen it).
Anyway I've addressed the issue on the server and it should slowly begin to affect every user. I'll keep this open to track changes.

**Comment by realdmitchell** [comment]
@daniele-athome Close/open/restart phone/Refresh several times still same problem :-(

**Comment by daniele-athome** [comment]
I should have fixed the server-side issue. I bumped into this issue myself a few times, I will do some experiments and get back to you.

**Comment by webratte** [comment]
> @webratte, you may delete that account if you wish, but I guess I'll be doing some tests locally to 
> speed up things (I can't wait a month to test it ;-) and I don't like to touch the production database 
> manually). Thanks anyway, I'll keep you posted.

Just for information @daniele-athome 
At 29.09.2015 I have deleted this account.
Now it's removed from Kontalk contact list without a trace.
It seems it's really fixed.  :+1:   
Thank you.
