### ISSUE TITLE
Watch for contact changes

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#574]
When changing a contact's picture, it is necessary to refresh the contact list. It would be nice if Kontalk could instantly pick changes like this up when they happen.

**Comment by daniele-athome** [comment]
Actually it's a cache mechanism. The picture is reloaded if have enough contacts to queue the older entries out of the cache or you restart Kontalk (kill the process and start it again).

There is a mechanism to watch for contact changes in Android, however it's triggered very often because it's one listener for all contacts (you can't watch single ones), and it's triggered also for events like a phone call, a SMS message (because of stats counters changes, which are stored in contacts). This means that whenever I get one of those signals, I need to invalidate the whole cache and reload  contacts information and avatars whenever I need them.
Despite this might not seem much of a performance impact, it actually is (it will make some activities load slower).

But: Android API 16 introduced onChange() method with a Uri argument, which I suspect will include the specific contact that has changed. In that case, it would be much lighter than invalidating the entire cache.

As a side note, I had this mechanism once (before API 16 came out), but I removed it for performance reasons. I will investigate.
