### ISSUE TITLE
Backup chats via Titanium

### ISSUE THREAD

**Issue by quizilkend** [kontalk/androidclient#575]
Hey,

if I Backup Kontalk via Tatanium Backup, switch ROMs and then restore, all my chats are gone. Do you know what's the issue behind that?

Thanks a lot,
Sammy

**Comment by TheLastProject** [comment]
I don't know about Titanium, but with oandbackup I have to first kill Kontalk completely before I restore data, otherwise it won't pick up the chats. Have you tried to completely close Kontalk (just "force stop" in Apps) and restore data then?

Also, with Kontalk, you probably want to back up your personal key and restore it during registering, otherwise your contacts will get a big "private key changed" warning. You may already be doing this, but it's worth noting just to be sure.

On 15 October 2015 10:13:08 CEST, quizilkend <notifications@github.com> wrote:
>Hey,
>
>if I Backup Kontalk via Tatanium Backup, switch ROMs and then restore,
>all my chats are gone. Do you know what's the issue behind that?
>
>Thanks a lot,
>Sammy
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/575

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quizilkend** [comment]
Thanks a lot!
That worked. To restore the backup I have to manually install Kontalk, then import the Keys, kill it via the settings and then rerstore only the data.

**Comment by WorldCodeCentral** [comment]
I can't believe this worked. How does that make sense? I've tried with both oandbackup and Titanium Backup and both are supposed to copy everything. I couldn't find anything on the sdcard, does it check for the key there somewhere I couldn't find?

But even then it makes no sense that it worked to restore on my previous device. I thought it was a bug in oandbackup because it worked when I tried with Titanium Backup. I'm so confused...

**Comment by daniele-athome** [comment]
@WorldCodeCentral I'm not following. Why shouldn't it work?

**Comment by WorldCodeCentral** [comment]
Because it didn't work without importing the key beforehand. How can Kontalk notice that I didn't import they key when I copied all of it's data with super user privileges? Did I miss some directory on the sdcard?

**Comment by daniele-athome** [comment]
So, Kontalk deletes all messages on two occasions:

1. account removal
2. any application startup when no account is registered (one specific case of this is *before importing the key*)

If I understand you correctly, even if Titanium restored all messages, importing the key would need to be done *next*, which would mean opening the app without an account, which would fall into case 2.
So it wouldn't be possible. Am I getting this right?

**Comment by WorldCodeCentral** [comment]
I guess you are right, but how come the backup apps do not restore the key like all the other data? (I restored the data immediately after installing so Kontalk should not have been running and deleting anything. I also tried after stopping the service/app manually.)

**Comment by daniele-athome** [comment]
Because the key is stored in the AccountManager, not in the app's data.
(Sorry for the delay, I've been trying to recover my email queue)

**Comment by WorldCodeCentral** [comment]
Hey, thanks a lot for getting back at me. I didn't know there was any relevant data outside the appdata so this is very useful for me to know :-) Hope you're done soon with all the mails ;)
