### ISSUE TITLE
Attachment upload and download fails

### ISSUE THREAD

**Issue by utack** [kontalk/androidclient#578]
When uploading or downloading an attachment it fails with, shown in adb, some kind of SSL error.
ADB error message:
http://pastebin.ubuntu.com/12841967/
It was introduced between 3.1-beta2 and 3.1-beta3 F-Droid version.
Happens on Wlan and mobile data, is reproducible 100% of the time.
Hope this is not a rom (Canogenmod 12.1) issue it triggers, but someone else reported it working on the same rom for another device.

**Comment by daniele-athome** [comment]
Thanks for reporting. Can you try again now?

**Comment by utack** [comment]
Force restarted Kontalk.
Same error.

**Comment by daniele-athome** [comment]
Ok, so it's some sort of SSL protocol incompatibility (nightmares coming). Which happens on CM 12, but not on stock Android 5.1.1. I'll investigate.
@utack I guess you've just upgraded to that Android version right? Or did it just stop working one day while always been using Android 5.1.1?

**Comment by utack** [comment]
@daniele-athome if I go back to 3.1-beta2 on that rom it works perfectly fine.

**Comment by daniele-athome** [comment]
So it's also related to the new switch to HttpUrlConnection. Thanks, I'll investigate also on that side.

**Comment by daniele-athome** [comment]
Ok there was a problem, however for some reason your OS version does not accept the custom certificate. The fix is actually a workaround, @utack please leave "Accept any SSL certificate" checked after upgrading to 3.1.1. Kontalk server is switching to StartSSL certificates, so this problem should not even occur anymore.

**Comment by utack** [comment]
I am still having this problem with 3.1.1 and "accept any ssl cert" enabled.
http://pastebin.ubuntu.com/13444666/
It must be a Rom issue I guess, so should I file a bugreport to Cyanogenmod?

**Comment by daniele-athome** [comment]
Thanks for reporting back @utack.
Debugging SSL issues is a pain and I really don't know if at this point it's a Cyanogenmod issue or a Kontalk issue. It's probably a bug in the internal HTTP/OpenSSL implementation of your CM version, so the only way to workaround it would be **maybe** by using an external HTTP library? And I really don't know if it could fix it this way either, because OpenSSL will still be the same on your device.
Please report to CM and let me know, maybe we can work together to fix this also on their side.

**Comment by daniele-athome** [comment]
I crawled around a bit into Android source code and I suspect there is some protocol error regarding the use of SSLv3 - which is disabled on the server, I don't know why CM12.1 is still using it, but whatever.
I've switched to using NetCipher (2e5e5fa) and it works ok on my device and on the emulator. @utack If I provide you with an apk with a different package name (so you can install it along with your current version), could you test it? You'll need to export your personal key and import it in this new version I'll give you so you'll have the same key (otherwise the old client will be kicked out).
