### ISSUE TITLE
Contextual reply

### ISSUE THREAD

**Issue by jinformatique** [kontalk/androidclient#594]
A feature request:
It would be nice to have a reply button for previous message like Telegram does.

**Comment by TheLastProject** [comment]
Could you take a screenshot of how Telegram does it? That would make it a lot easier for us to know what you mean.

On 12 November 2015 12:56:31 CET, Jean Elchinger <notifications@github.com> wrote:
>A feature request:
>It would be nice to have a reply button for previous message like
>Telegram does.
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/594

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by juanito003** [comment]
When taping on a message from the conversation, you get these options:


![01](https://cloud.githubusercontent.com/assets/487038/11121483/668fd0ae-8956-11e5-99d8-47a32972d762.png)

I selected "Reply". The message appears just over with the person's name.

![02](https://cloud.githubusercontent.com/assets/487038/11121482/668e84c4-8956-11e5-9b00-8659a97bdbdf.png)

And then sending the message, it appears like this:

![03](https://cloud.githubusercontent.com/assets/487038/11121484/66902b80-8956-11e5-82fa-3c679a459ed6.png)

**Comment by webratte** [comment]
IMO in 1:1 chats it's not so important.
But I think this feature would be very helpfull in groupchats.

**Comment by bastoGrande** [comment]
@webratte: sorry, but it is very important to me, even in a 1:1 chat. Imagine you chat with someone, who is typing like speedy gonzales? And you just cannot keep up to reply to his messages. So sometimes this gets very confusing in a chat. This can help to improve the quality of your chats a lot! Seriously, a lot!

I really want this for the next release! I would even donate for this feature (I already donated this year twice). It is seriously a show-stopper and I think it is easy to implement, but correct me if I'm wrong.

@daniele-athome 
What do you need: 
1. Take the original message.
2. Put it quoted at the end of the chat and give the opportunity to reply to it as well. So that the new message is either on top of the quote or below it. I prefer below it. So you have the original message with a following new message.
3. Put a reference anchor on the quoted message. So if you click the quote, the position of the chat moves backwards to the position of the original quoted message.

Any more infos needed?

**Comment by daniele-athome** [comment]
- [ ] XEP to use

[Probably this one](https://xmpp.org/extensions/xep-0372.html#usecase_previous), but I'm not sure of some side effects.

Anyway it's not a matter of importance here, but of development power and time. Just a reminder that I'm currently developing alone in this period of time, with some help from time to time by @acappelli, but that's about it. I'll try to raise the priority of this feature, but there is so much work to do that I really can't be sure how much priority I can give to this.

As always, if someone would take over development of this feature, I'd be happy to give some pointers to him/her :-)

**Comment by BlauerHunger** [comment]
Maybe you could do this like in Conversations >=1.15.1

**Comment by bastoGrande** [comment]
Ok, will try my best and research for the best XEP(s) and try'll to narraw down the code-spots to implement it finally.

Like I said, it's a show-stopper. Sure group-chat will convince people from Kontalk! But little gifts here and there can have quite the same effect even if it's from the programmatical view of point not the same amount of work.

@BlauerHunger 
I'll check that as well.

**Comment by bastoGrande** [comment]
Ok, note to myself: never promise something that you didn't check first.

Well, I tried to understand the whole idea of XEP(s) and how to implement and when I understood it right, first the server needs to support the XEP before you can implement it in the kontalk-client. So there is the first problem: the two dependencies ([0030](http://xmpp.org/extensions/xep-0030.html) and [0115](http://xmpp.org/extensions/xep-0115.html)) which need to be implemented before [0372](http://xmpp.org/extensions/xep-0372.html) are supported by the tigase-server, but the 0372 itself not. 

So first there is a lot of work to implement three XEP(s) and finally not yet possible because of server-limitation. And if I got the roadmap of the tigase server right, they are not planning to implement it in the near future.

Didn't forget to check conversations, but will do this later.

**Comment by daniele-athome** [comment]
I believe 372 can be used as a client only extension in this case, so no involvement of the server. The implications I was thinking about concerns the use of message ids as reference instead of quoting the actual text (the latter doesn't have a xep yet, and I believe it's more suited to our use case, not mentioning more reliable).

**Comment by daniele-athome** [comment]
On a more serious study, neither 372 nor `<thread/>` element are quite correct. I'll probably have to use [message forwarding](https://xmpp.org/extensions/xep-0297.html), even if it's not strictly a forward, since it's the only one allowing mentioning of a whole message stanza.
