### ISSUE TITLE
Non-latin characters fall under the "others" indexed section

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#601]
Until 3.1 sorting of unicode names was in alphabetic order, in 3.1.1 all unicode names are clubbed as special characters under #.

**Comment by daniele-athome** [comment]
Thanks for reporting. @acappelli would you mind looking into this whenever you have the time?

**Comment by TheLastProject** [comment]
I assume this to be caused by ContactListAdapter being hardcoded to #ABCDEFGHIJKLMNOPQRSTUVWXYZ

See https://github.com/kontalk/androidclient/blob/42a701408ebac3ef2d1ebf198f0af606b6c46b0a/app/src/main/java/org/kontalk/ui/adapter/ContactsListAdapter.java#L49-L50.

**Comment by daniele-athome** [comment]
I'm also guessing it's related to that, however we can't put every letter in every alphabet inside that string :-) we definitely have to find another way.

**Comment by pravi** [comment]
Can we revert to old listing?

**Comment by daniele-athome** [comment]
@pravi it would have the same problem.

**Comment by daniele-athome** [comment]
Introducing ICU4J for correct collation incremented the apk size to 18 MB. I don't think this is going to be an option (despite I've implemented it and it's fully working).
The increment in size is due to the ICU data files inside UCI4J. So, unless we fork the library to produce a reduced version with only the necessary stuff (unfortunately Proguard doesn't help in this case), I don't think this can be fixed easily.
Besides, the code I took from AOSP takes into account some other rules with non-latin languages that should be taken care of.

I'm currently working on an much more limited alternative to ICU4J, but one that should do the job.
