### ISSUE TITLE
The personal key for this user changed unexpectedly !

### ISSUE THREAD

**Issue by strk** [kontalk/androidclient#609]
I've re-registered from a new device as I could not import the keys from the old one (either forgot the password or not working for some other reason).

In any case now that I re-registered I keep getting the "The personal key for this user changed unexpectedly!" whenever I select a contact. Hitting "details" goes on about verifying with the user that she/he reinstalled kontalk etc. etc.

But it was _me_ changing key, not everyone else !

**Comment by daniele-athome** [comment]
That's because trust is per-device and not per-account. There is a ticket open for that #505. I still have to decide if it's a security matter that should be linked to the key (e.g. inside the kontalk-keys.zip file) or to the roster (e.g. stored in the server). Probably the former.

**Comment by strk** [comment]
So you're saying that right now my contacts public keys are stored in kontalk-keys.zip, which I failed to import ?

In any case this is an UX ticket, in that the message implied the party key was _changed_ while instead if it was in the kontalk-keys.zip it was _missing_, not changed.

**Comment by daniele-athome** [comment]
> So you're saying that right now my contacts public keys are stored in kontalk-keys.zip, which I failed to import ?

No sorry I've explained myself badly. I'm considering storing trust settings (that is, which users do you trust with their keys and which youy don't) inside the kontalk-keys.zip (e.g. in a plain text file). But for now they are stored in the app settings, so if you change device or register from scratch you will lose them and the app will ask you to trust them again because it doesn't know that you do.

> In any case this is an UX ticket

Indeed, that's another necessary change: "key has changed" is different from "key is unknown".
