### ISSUE TITLE
Unable to register new device

### ISSUE THREAD

**Issue by marc0s** [kontalk/androidclient#655]
Already seen #585 but proposed workaround didn't work.

Environment: a new device, registering with the same phone number than the one used in the old device.

Missed call is received and last 4 digits introduced.  When submitting the information, after the waiting screen disappears, the same register screen is shown (the one asking for the name and the phone number, but already filled in).

Unable to get out of this loop, tried with 4 or 5 calls with no success.  Also tried to click on "no call received" button to see if any SMS is received but no luck, no alternative is proposed nor received.

**Comment by daniele-athome** [comment]
Thanks for reporting. I've already heard about this issue, but I was never able to reproduce it.
Let's try to figure this out for good this time.

* What device is it?
* Android version? Stock or custom?
* Do you have root and/or some hacking tools such as Xposed?
* Any particular settings you might have tweaked in Android developer options?

**Comment by marc0s** [comment]
It's a Fairphone 2, stock ROM: android 5.1, no developer options modified at all and no rooted device.

**Comment by TheLastProject** [comment]
Fairphone has a bug with their app to track what permissions apps use, the fix was disabling and then reenabling that app (somewhere in settings? Not sure, don't have a Fairphone). Have you tried that yet? I remember it fixing issues with F-Droid.

On 25 February 2016 12:19:19 CET, marc0s <notifications@github.com> wrote:
>It's a Fairphone 2, stock ROM: android 5.1, no developer options
>modified at all and no rooted device.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/655#issuecomment-188736615

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
@marc0s: Thanks, I'm going to try with an emulator and get back to you.
As a sidenote, I've probably just found a bug in the registration code but it shouldn't be related to this issue.

@TheLastProject: are you talking about this: https://forum.fairphone.com/t/f-droid-stopped-working-properly/13496

**Comment by TheLastProject** [comment]
That link is indeed what I mean, yes

On 25 February 2016 12:29:35 CET, Daniele Ricci <notifications@github.com> wrote:
>@marc0s: Thanks, I'm going to try with an emulator and get back to you.
>As a sidenote, I've probably just found a bug in the registration code
>but it shouldn't be related to this issue.
>
>@TheLastProject: are you talking about this:
>https://forum.fairphone.com/t/f-droid-stopped-working-properly/13496
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/655#issuecomment-188741540

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marc0s** [comment]
Thanks to @TheLastProject link and information I was able to workaround the issue.  Doing the registration process again with privacy track disabled did the trick.

So, seems that's not a bug in Kontalk at all and that should be fixed in the upgrade for the FP2 ROM.

Thanks!

**Comment by daniele-athome** [comment]
I don't even know how to workaround that. I mean without proper debugging with the device itself.
The root cause could be a few:

* onActivityResult being called with wrong result or request code
* onActivityResult not being called
* returned activity not being resumed correctly
* some other weird thing

@TheLastProject I can't find anything on how F-Droid handled it, do you know if they actually did or did they just drop the issue?

**Comment by TheLastProject** [comment]
@daniele-athome [They dropped the issue](https://gitlab.com/fdroid/fdroidclient/issues/567).

**Comment by daniele-athome** [comment]
Ok thank you.
