### ISSUE TITLE
Improvement/clarification of menu concerning missing push feature

### ISSUE THREAD

**Issue by keynlotepan** [kontalk/androidclient#749]
When I installed Kontalk yesterday I initially was happy since it exactly seems to meet my requirements and worked well. Some hours later I used it again but the message apparently did not reach the receiver. So I searched within the menu what could be wrong. I found that there is no push support on my device. I looked in the internet and found the (very creditable) cause that Google services are no longer used ("his version has been stripped of all Google components, meaning no support for push notifications."). This was the moment I decided to look for other messengers because a messenger which must be polled manually does not make any sense to me. Fortunately, later I got a message without manually polling - my device was "sleeping" besides me and suddenly flashing. So there must be some kind of automatic polling process I did not expect after all what I read.

To cut a long story short here is a list of proposals for menu improvements:
- The menu tells me there is no push support _on my device_, the internet (F-Droid page) tells me there is no push support _at all_. This is inconsistent - please clarify.
- Please give a hint close to the disabled push notifications checkbox (or on touch) that this does not mean that the user will not receive any messages during device idle mode or app background mode but it might take some time. Otherwise Kontalk is in danger to be rated by the user to be useless.
- There are two items in the maintenance menu (first: disconnect timeout in idle state, second: reconnect to server) which apparently do not deal with maintenance. I think it is better to locate them in the network menu (particularly since they seem to be associated with "push disabled" matters mentioned above)
- the above mentioned menu item "reconnect to server" should be disabled when push is not supported instead of describing its inapplicability textually

And after all this criticism here comes a hue compliment: Kontalk is great.

**Comment by daniele-athome** [comment]
Thanks for your very useful insights. I've addressed your concerns below, please comment wherever you can/want.

> The menu tells me there is no push support on my device, the internet (F-Droid page) tells me there is no push support at all. This is inconsistent - please clarify.

Totally right.

> Please give a hint close to the disabled push notifications checkbox (or on touch) that this does not mean that the user will not receive any messages during device idle mode or app background mode but it might take some time. Otherwise Kontalk is in danger to be rated by the user to be useless.

Actually, the preference doesn't state that, it simply says that "it saves battery". In theory, when this checkbox is unchecked or disabled, Kontalk should stay always connected. However, that behaviour can also be controlled by the other options in the maintenance section, so I agree to make the whole thing at least more consistent (e.g. two behaviours only: one with push, one without).

There is a lot of confusion among users on the meaning of "push notifications" (partly due to the definition used by Apple); some users believe that if you disable push notification you won't receive messages anymore.

Since putting a dialog on the checkbox click is out of the question (bad UX), I could:

* make a dedicated window for the preference, explaining the effects of enabling or disabling it, or
* (connected to your 3rd point) move all the connection policy related preferences into a dedicated section where they might be understood better (because of more context around)

> There are two items in the maintenance menu (first: disconnect timeout in idle state, second: reconnect to server) which apparently do not deal with maintenance. I think it is better to locate them in the network menu (particularly since they seem to be associated with "push disabled" matters mentioned above)

Indeed, as stated above, I'd create a dedicated section for those preferences.

> the above mentioned menu item "reconnect to server" should be disabled when push is not supported instead of describing its inapplicability textually

Ehhr it is actually used in a borderline case also when push notifications are enabled. If there is a network connectivity issue, after 10 connection attempts Kontalk give up and tries again after the "reconnect to server" interval. I know, I know, it can be improved :-)

**Comment by daniele-athome** [comment]
I've addressed the first part of this issue by separating the push notifications preference to its own window, with a quick explanation (#823, needs review, especially for the message showed :-)

I'll now bring some order to those maintenance preferences.

**Comment by daniele-athome** [comment]
Closed in d7b632b60c28391f0d7c2f82ee039b0a55db2d64.
