### ISSUE TITLE
Inserting text from clipboard into message not supported

### ISSUE THREAD

**Issue by keynlotepan** [kontalk/androidclient#768]
Having some text in my clipboard (Version 3.1.10 on CM11) and long tapping the message input text control does not open dialog/controls to insert clipboard content.
This would be very useful to 
- send links
- send output from other apps (e.g. train time table)
- cite previous messages

**Comment by TheLastProject** [comment]
Are you absolutely sure you have valid plain text in your clipboard? Can you paste it in other apps? I'm asking because it works for me and has worked for as long as I remember.

![tmp_19425-screenshot_20160618-095130-943151832](https://cloud.githubusercontent.com/assets/1885159/16169782/65e5e92c-353b-11e6-9ad1-94278d54c90f.png)

**Comment by keynlotepan** [comment]
Absolutely sure. I am able to insert the textual single word clipboard content into K9 and into Google input field in Firefox. But in Kontalk only the blue indicator showing the input position (the blue 'drop' in your screenshot) appears but not the 'paste' button above. Independently of the input method (Swype or AOSP).

**Comment by daniele-athome** [comment]
> Pausing imprecating on Google

Just to see if it's an app problem or a [composer bar](https://github.com/kontalk/androidclient/blob/master/app/src/main/java/org/kontalk/ui/view/ComposerBar.java) specific issue, does the search text entry work? I mean can you paste into it?

> Resuming imprecating on Google

**Comment by keynlotepan** [comment]
Exactly the same error in the search text entry.
Some additional informations
- Gapps are not installed on my phone
- My Kontalk installation comes from F-Droid
- I just tested this on a couple of apps and did not observe this error on any of them
- The app "Copy To Clipboard" is installed on my phone
- When I switch permission to "query user for permission to read from clipboard" there is no OS query about whether the app should be allowed to read from clipboard during this incidence
- But privacy center tells me that reading from clipboard was granted one single time (maybe during installation?)
- Clipboard writes (from previous messages and from text input) work well

**Comment by daniele-athome** [comment]
> When I switch permission to "query user for permission to read from clipboard" there is no OS query about whether the app should be allowed to read from clipboard during this incidence

Could you disable privacy center for a moment and try again? If it works, I can focus my research on the privacy center because otherwise I'm clueless.

**Comment by keynlotepan** [comment]
Disabled privacy protection (via privacy setting menu or via "app info" (see screenshot)) does not help. Error also is present in the dialog where I can enter a text about my state.
![screenshot_2016-06-19-20-45-42](https://cloud.githubusercontent.com/assets/11136173/16179217/76ca0154-365f-11e6-9055-2fad707372d5.png)

**Comment by daniele-athome** [comment]
Ok then. Let's see what the system says. Can you produce a full system log from app start until a paste action is attempted please? Please send it to the devteam email address. You can use the Catlog app from F-Droid to send one directly via email. I'll begin my research on possible causes (I have another one in mind besides Privacy Guard). Thanks!

**Comment by keynlotepan** [comment]
Did you receive my log yesterday and was it extracted correctly?

**Comment by daniele-athome** [comment]
@keynlotepan yes I did sorry, but i had no time to look at it yet. I'll let you know ASAP.

**Comment by daniele-athome** [comment]
Hello again, sorry for the delay. I'm afraid nothing came up from the log and since it's an app-wide issue I'm guessing it's because of the support library/appcompat or the way the appcompat theme is used. For now I'm going to provide you with an apk built from master using appcompat v24 just released a few days ago. You can install it along with your existing Kontalk version (it'll be using a violet-ish icon in the launcher). You'll just need to start it up and try a paste into the name text entry in the registration dialog (you should not register again).
Here is the URL to the apk: http://astra.casaricci.it/public/Kontalk-issue-768.apk
Thanks for your help and your patience!

**Comment by daniele-athome** [comment]
For verifying purposes (since it's HTTP only), here is the sha1sum of the file: e660902d9c5bc31cffaa3786832247bd5eb1919f

**Comment by keynlotepan** [comment]
I compared the same dialog field (text input to configure server address manually) within standard app and test app and in the latter pasting worked!

**Comment by daniele-athome** [comment]
So it's probably appcompat and/or support library. I'm sorry but you'll have to wait for version 4.0 to come out. A first alpha version will be released soon (somewhere in July).
