### ISSUE TITLE
Crash on key exporting

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#780]
Can't use Kontalk on other device because I can't export zip archive with key. After entering the correct password application crashes!
Ask me for logs you are interested in and I'll attach them.

**Comment by daniele-athome** [comment]
Thanks for reporting. Please produce a full logcat right after the crash occurs. The log might contain sensitive data, you should not attach it here. Please send it to devteam (at) kontalk.org.

**Comment by daniele-athome** [comment]
I got the log, thank you. Device brand/model and Android version/firmware type?

**Comment by Buranek** [comment]
LG P-715 Android 4.4.2
Kernel Version: 3.4.0
Build no: KOT-49I.P71520a_ViT
Version: P71520a

Firmware is based on official, author added root and changed SD card mount point as I remember. I also can assure you that other apps haven't got any problems with saving files either to internal memory (storage/emulated/legacy) or external SD (storage/external_SD).

**Comment by daniele-athome** [comment]
Since there is no indication of any bug in the application and other Android flavors/firmwares work correctly, and there is a history of non-conforming firmwares (unfortunately no proof for LG yet), I'm going to fall back to pre-Kitkat behaviour when the Storage Access Framework method doesn't work (like in your case). Current app permissions should work, at least for the internal memory.

**Comment by daniele-athome** [comment]
By the way, does selecting a picture from gallery (attach icon in Kontalk > Gallery) work?

**Comment by Buranek** [comment]
> By the way, does selecting a picture from gallery (attach icon in Kontalk > Gallery) work?
No, since I have deleted default gallery and using QuickPic instead of it.
And attaching from QuickPic to Kontalk works. But attaching from Kontalk can work only with default gallery. And that's not comfortable.

**Comment by daniele-athome** [comment]
> But attaching from Kontalk can work only with default gallery. And that's not comfortable.

That is QuickPic not implementing Storage Access Framework at all. Starting from Android Kitkat, Google has made clear that SAF should be used to access user files instead of reading directly from the file system.
That said, I can either use SAF **or** direct file system access, not both &mdash; I can only do like what I did in ef4f2dc4f2dc0205eabf75be212c79740aee155d: if trying SAF throws an error, I'll use the old file chooser dialog.

By the way, it is really strange that it crashes on your device. I mean even if you don't have the stock gallery, there must be other document providers installed on your system, such as the Download Manager. Anyway, I'll implement the workaround as described. Thanks for your help!

**Comment by Buranek** [comment]
I can tell you that selecting another background works fine. I think you can use the same technology to select photos from gallery. So QuickPic will also work.

**Comment by daniele-athome** [comment]
As a matter of fact, that part does use the old method, but only because I forgot to switch to the new one :-)
