### ISSUE TITLE
Unable to register on Jolla

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#799]
On Jolla is unreal to use Kontalk because it blocks reading of contacts via Android virtual machine. I guess you can perform a workaround. The registration is failed, and application is going in cycle segfault with bunch of different errors.

**Comment by daniele-athome** [comment]
I thought this was addressed on #616. Could you provide a system log for analysis please?

**Comment by Buranek** [comment]
What kind of log do you need? Logcat or native log from Jolla?

**Comment by daniele-athome** [comment]
I don't know how it works on Jolla, but I guess a logcat should do.

**Comment by Buranek** [comment]
Log will be soon.

**Comment by Buranek** [comment]
Sent. Check your mail.

**Comment by daniele-athome** [comment]
I read the log, thank you. Unfortunately the exception didn't came through from the Contacts Provider, so it was not reported correctly (because it shouldn't happen). I could put more checks and skip contacts sync altogether if some error occurs, but that's pretty much all I can do.

@Buranek is blocking the contacts by design in the Sailfish OS or have you activated something or set something to block them?

**Comment by Buranek** [comment]
Yes, it's blocking contacts by design in Sailfish OS.

**Comment by daniele-athome** [comment]
Ok, I could handle missing contacts in a better way, but what would be the point? I mean no contacts mean no people to talk to, am I right? How are you supposed to use Kontalk anyway?

**Comment by Buranek** [comment]
Add a workaround to load contacts from vcf.

**Comment by daniele-athome** [comment]
Oh, that's a very easy workaround :P
Seriously it's not so easy to implement right now. Another issue is already open for manually adding contacts, but for now I have to reject this, sorry.

**Comment by TheLastProject** [comment]
As written in #616 there is obviously a way to give apps contact access. It seems to me like Kontalk should somehow detect running in Jolla and ask users to enable contact access if not enabled. Maybe @fabrixxm can tell us more about how possible this is, also if it works well on Sailfish currently when allowed.

**Comment by fabrixxm** [comment]
On Jolla, you can enable Android app to read system contacts. As well as you can enable background processes for Android apps (aren't enabled by default).
To enable access to contacts, open Settings, tap on "Android Support" and enable "Allow Android apps to access your contacts" (label text could vary, mine is in Italian :-) )
Las time I tried, registration went fine, I'm happly using Kontalk on Jolla from a while, now...
#616 fixed a bug raised because Android apps on Jolla are unable to *write* to contacts, but writing is not fundamental for kontalk to work..

To activate background jobs for Kontalk, in Settings, tap on "Applications >", then on Kontalk icon..
