### ISSUE TITLE
need 3 categories of groups

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#835]
Without this option, it would be very inconvenient to use groups in kontalk for the other categories.

1. Everyone know each other and only admin can add members.
2. Members may add other members. In this case, expecting everyone to verify everyone else makes it hugely inconvenient because admin has to share contact details of all new members to existing members. A private muc will suit better here.
3. Public groups like irc. This is impossible with current groups implementation. A public muc will fit here.

Having to use a pure xmpp client for these two use case is a waste of battery and extra hassle of maintaining an xmpp account.

**Comment by TheLastProject** [comment]
Telegram has all three types in one. The group can be configured to only allow admins to invite members or allow everyone to. It also provides "invite links" that allow people to join by following the link, which only the admins can access but obviously can share.

Requiring verifying is indeed extremely inconvenient and makes inviting someone into a bigger group basically impossible. This is why I talked about using TOFU before, so that new members are immediately trusted and only untrusted if their key changes.

**Comment by daniele-athome** [comment]
Since the new group feature (and protocol) is somewhat experimental, for the moment we're implementing admin-only management of groups. So for now I'm going to reject this, sorry. Depending on user feedback (after 4.0 release) we'll see how to proceed.
