### ISSUE TITLE
Media uploaded twice

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#849]
Something is triggering pending message sending twice, causing pending media to be sent twice (duplicated message id so the receiver doesn't notice it).

Cause: mWaitingReceipt is filled with outgoing message id only during the 2nd stage (XMPP send), so in some rare conditions it can trigger a double upload.

**Comment by TheLastProject** [comment]
Did you see this happen more often? I don't recall noticing this but 2 days ago Kontalk kept 4 pictures I tried to send to a friend on pending so I restarted the message center. Just want to double check this issue wasn't just me restarting the message center because I was being impatient.

**Comment by daniele-athome** [comment]
@TheLastProject this bug in particular only affects version 4.0 alpha - IIRC you're still on version 3 and it should work just fine. Can you reproduce it on version 3 too?

**Comment by TheLastProject** [comment]
I definitely didn't notice it happen on version 3. I just wanted to make sure it wasn't just me causing something weird when restarting the message center (although I did not see anything weird happen) because of the timing this issue was created. If you've seen it on 4.0 then it clearly wasn't related to my restarting of the message center on 3 and you can ignore my comment :)

**Comment by daniele-athome** [comment]
Ok :-)
