### ISSUE TITLE
Can't chat with group even after kicking all unauthorized contacts

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#870]
### Expected behavior
I can send messages to the group because all members are authorized.

### Actual behavior
Although all members have the ✅, Kontalk still displays

>You can't chat with some of the group members because you haven't been authorized yet. Open a private chat with unknown users first.

I assume this is because there was an unauthorized contact before (remember #862?). I have kicked that contact now, but it seems Kontalk doesn't take the new situation into account.

### Steps to reproduce
1. Start a group chat with 2 authorized, 1 unauthorized person and yourself.
2. Kick the unauthorized person.
3. Try to send a message to the group.

### Environment

Kontalk version: Beta1-basic

Android version: Kitkat 4.4.2

Device model: Fairphone 1

**Comment by daniele-athome** [comment]
Thanks for reporting! I'll fix it ASAP.

**Comment by StefanBrand** [comment]
OK, the problem was not the unauthorized contact that I kicked, but that someone else in the group hadn't accepted me. (It wasn't clear to me as all people had that green check mark.)

**Comment by daniele-athome** [comment]
Yes I also saw that one earlier. I'll fix both issues.

**Comment by StefanBrand** [comment]
Sorry, I deleted my previous comment because I thought I was mistaken. Then it's indeed two issues. :)

**Comment by daniele-athome** [comment]
> Note to self

When starting a group with unauthorized members and remove them right after creation, the create command won't be sent because the initial creation command contained the unauthorized users. Consider removing the removed members directly from the create command (and from group members too) so that the create command appears as if it were created without the removed users. **Beware race conditions against the message center trying to send the commands**

**Comment by StefanBrand** [comment]
Confirmed, works in [latest beta](https://forum.kontalk.org/t/preview-kontalk-for-android-4-0-0-beta1-preview/75?u=stefan).
